#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a well-known
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Add config xml
sed -i "s@DOMAINTOCHANGE@$domain@g" ../conf/config-v1.1.xml
sudo mkdir -p /var/www$path/autoconfig/mail/
sudo cp ../conf/config-v1.1.xml /var/www$path/autoconfig/mail/config-v1.1.xml

#skip config path /$path/autoconfig/mail/config-v1.1.xml
sudo yunohost app setting well-known skipped_urls -v $path/autoconfig/mail/config-v1.1.xml

# Configure Nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/well-known.conf

# And reload
sudo service nginx reload
sudo yunohost app ssowatconf

echo $?
